### ISSUE TITLE
What should this be named? Is it a built in module or a global namespace?

### ISSUE THREAD

**Issue by maggiepint** [maggiepint/proposal-temporal#12]
Currently the working name is "temporal", but concerns were voiced in #10 about this.

Agree it may not be a perfect name. What does make sense?

**Comment by Turbo87** [comment]
I had a few unstructured thoughts about this:

- the internationalization code is grouped in the `Intl` namespace now, which is capitalized. Maybe it should be `Temporal` instead of `temporal` then?

- should we use `DateTime.Local` and `DateTime.Zoned` instead? but then again for the current proposal that might make sense but if we want to add functionality in the future it might not fit as well.

**Comment by apaprocki** [comment]
If the built-in route is chosen, the name would also have to be a reserved keyword. Something like `Temporal` is probably much less common than other words, but I'm not sure about how research was done before adding prior new reserved keywords. The built-in module route is certainly much safer.

**Comment by domenic** [comment]
Why would it have to be a reserved keyword? It can just be any name, like all the other globals we've added recently (e.g. Reflect).

**Comment by apaprocki** [comment]
@domenic Sorry, was under the impression that the built-ins were reserved in some manner. Strike that!

**Comment by hollowdoor** [comment]
I happen to like the name. As far as module vs. global I think all apis that aren't primitives should be modules, but that's impossible. :)

**Comment by mj1856** [comment]
Sticking with `temporal`.  Thanks for the feedback!
