### ISSUE TITLE
Consistent use of singular/plural form

### ISSUE THREAD

**Issue by kirilloid** [maggiepint/proposal-temporal#40]
Currently, these objects use singular form for fields, but accept plural forms in arguments for e.g. `plus`. So we cannot even use that new type as a date range and add it to existing.

Use case:
```javascript
// constructors are used with different API for clarity
const delta = new CivilDate({ month: 1 });
let current = new CivilDate({ year: 2017, month: 1 });
while (date.year < 2018) {
  layoutCalendarMonth(date);
  date = date.plus(delta);
}
```

**Comment by mj1856** [comment]
Thanks for the feedback.  Glad you noticed that they are different.  That is intentional, and aligns with how units are typically used in English.

- When referring to a _quantity_ of an item, it is conventional to use the plural form of a unit.  For example, "How many stories high is that building?".  The answer could be also plural ("ten stories"), or singular ("one story").

- When referring to the _position_ of an item, it is conventional to use the singular form of a unit.  For example, "Which story of the building is the office in?"   The answer is always singular ("the first story", "the third story").

Thus, when referring to a quantity of temporal units, such as the `plus` function does, the units are labeled with their plural forms.  When referring to the position of a calendar or clock, such as the civil-time objects do, the units are labeled with their singular forms.

Note that the units on an `Instant` object are labeled with their *plural* forms, as the represent a quantity of those units since the epoch, rather than a position on a clock or calendar.

A few other things from your sample code:

- We would never construct a `CivilDate` (or any other object) using an options object.  Doing so would lead to possible invalid states, such as a date without a year, or a time with a minute but without an hour.
- It would not be valid to represent a duration using a `CivilDate` object as you did with `delta`.  Other languages may have a `duration` , `period`, or `timedelta` for this, but we are not proposing one in this API.

**Comment by kirilloid** [comment]
I understand that plural forms reads more natural. Options object was just the result of my laziness, not related to request.
So the answer is: object is not intended to be used as time delta and added to each other. That's understandable, not any type can be added together. Adding two pointers in C doesn't make sense—only pointers + numbers is valid.

**Comment by mj1856** [comment]
Yep, exactly.  We thought about having `Duration` and `Period` types, but took a hard look at keeping the proposal to a minimum decided that it wasn't necessary.  Thanks for making me document the rational with the singular/plural forms though! 😄
